# Generated by Django 3.0.4 on 2020-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=100, null=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('daily_ration', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
