# Generated by Django 3.0.4 on 2020-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('deceased', 'deceased'), ('for adoption', 'for adoption'), ('stay', 'stay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], max_length=100, null=True),
        ),
    ]
