# Generated by Django 3.0.4 on 2020-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20200322_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('deceased', 'deceased'), ('for adoption', 'for adoption'), ('stay', 'stay'), ('adopted', 'adopted')], max_length=100, null=True),
        ),
    ]
