# Generated by Django 3.0.4 on 2020-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20200322_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
